[target.x86_64-unknown-linux-gnu]
pre-build = ["export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y software-properties-common && add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ focal main universe\" && apt-get update -y && apt-get install -y libgpgme-dev && apt-get install -y libgpg-error-dev"]

[target.aarch64-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture arm64 && export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y software-properties-common && add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ focal main universe\" && apt-get update -y", "apt install -y libgpgme11-dev:arm64 libassuan-dev:arm64 libgpg-error-dev:arm64",]

[target.i686-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture i386 && export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y software-properties-common && add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ focal main universe\" && apt-get update -y && apt-get install -y libgpgme-dev:i386 && apt-get install -y libgpg-error-dev:i386"]


